CREATE TABLE public.fomulario_dados_pessoais (
	data_nascimento date NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	cpf varchar(255) NULL,
	cpf_bolsista varchar(255) NULL,
	email varchar(255) NULL,
	fullname varchar(255) NULL,
	gender varchar(255) NULL,
	login varchar(255) NULL,
	num_educasenso varchar(255) NULL,
	"password" varchar(255) NULL,
	pcd varchar(255) NULL,
	phone varchar(255) NULL,
	username varchar(255) NULL,
	CONSTRAINT fomulario_dados_pessoais_pkey PRIMARY KEY (id)
);