CREATE TABLE public.endereco_candidatos (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	atividades_contraturno varchar(255) NULL,
	bairro varchar(255) NULL,
	cep varchar(255) NULL,
	cidade varchar(255) NULL,
	email_confirmacao varchar(255) NULL,
	endereco varchar(255) NULL,
	ponto_referencia varchar(255) NULL,
	residencia varchar(255) NULL,
	responsavel_legal varchar(255) NULL,
	segmento_2025 varchar(255) NULL,
	telefone_celular varchar(255) NULL,
	telefone_residencial varchar(255) NULL,
	telefone_trabalho varchar(255) NULL,
	tempo_deslocamento varchar(255) NULL,
	transporte_educacional varchar(255) NULL,
	CONSTRAINT candidatos_pkey PRIMARY KEY (id)
);