CREATE TABLE public.usuario (
	is_first_login bool NULL,
	role_id int4 NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NULL,
	"password" varchar(255) NULL,
	"token" varchar(255) NULL,
	user_name varchar(255) NULL,
	CONSTRAINT user_info_pkey PRIMARY KEY (id),
	CONSTRAINT fkibudjndsm0mcilkd0jcjgrjp8 FOREIGN KEY (role_id) REFERENCES public.roles(id)
);