CREATE TABLE public.form_condicoes_habitacionais (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	abastecimento_agua varchar(255) NULL,
	esgoto_sanitario varchar(255) NULL,
	estrutura_fisica varchar(255) NULL,
	fornecimento_energia varchar(255) NULL,
	situacao_imovel varchar(255) NULL,
	tipo_imovel varchar(255) NULL,
	CONSTRAINT form_condicoes_habitacionais_abastecimento_agua_check CHECK (((abastecimento_agua)::text = ANY ((ARRAY['EXISTENTE'::character varying, 'INEXISTENTE'::character varying])::text[]))),
	CONSTRAINT form_condicoes_habitacionais_esgoto_sanitario_check CHECK (((esgoto_sanitario)::text = ANY ((ARRAY['EXISTENTE'::character varying, 'INEXISTENTE'::character varying])::text[]))),
	CONSTRAINT form_condicoes_habitacionais_estrutura_fisica_check CHECK (((estrutura_fisica)::text = ANY ((ARRAY['ALVENARIA'::character varying, 'MADEIRA'::character varying, 'TAIPA'::character varying])::text[]))),
	CONSTRAINT form_condicoes_habitacionais_fornecimento_energia_check CHECK (((fornecimento_energia)::text = ANY ((ARRAY['COMPANHIA_ELETRICA'::character varying, 'GERADOR'::character varying, 'OUTRO'::character varying])::text[]))),
	CONSTRAINT form_condicoes_habitacionais_pkey PRIMARY KEY (id),
	CONSTRAINT form_condicoes_habitacionais_situacao_imovel_check CHECK (((situacao_imovel)::text = ANY ((ARRAY['PROPRIO'::character varying, 'FINANCIADO'::character varying, 'CEDIDO'::character varying, 'ALUGADO'::character varying, 'COMPARTILHADO_COM_OUTRA_FAMILIA'::character varying])::text[]))),
	CONSTRAINT form_condicoes_habitacionais_tipo_imovel_check CHECK (((tipo_imovel)::text = ANY ((ARRAY['CASA'::character varying, 'APARTAMENTO'::character varying, 'OUTRO'::character varying])::text[])))
);