CREATE TABLE public.fomulario_dados_parentes (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	parent1cpf varchar(255) NULL,
	parent1full_name varchar(255) NULL,
	parent1marital_status varchar(255) NULL,
	parent1phone varchar(255) NULL,
	parent2cpf varchar(255) NULL,
	parent2full_name varchar(255) NULL,
	parent2marital_status varchar(255) NULL,
	parent2phone varchar(255) NULL,
	resides_with_both_parents varchar(255) NULL,
	CONSTRAINT fomulario_dados_parentes_pkey PRIMARY KEY (id)
);